### ISSUE TITLE
Add black liturgical colour

### ISSUE THREAD

**Issue by tukusejssirs** [pejulian/romcal#200]
Although black liturgical colour can (and usually is) substituted by purple, so can be pink substituted by purple and we still list pink as a separate colour (although pink is much more often used by priests than blank).

Black can be used on All Soul’s Day and during Requiem Masses ([src](https://en.wikipedia.org/wiki/Liturgical_colours)).

**Comment by emagnier** [comment]
For simplicity we will continue to use the purple color only and will not introduce the black color. Then everyone is always free to customise the color based on the celebration color code.

**Comment by tukusejssirs** [comment]
> For simplicity we will continue to use the purple color only and will not introduce the black color. Then everyone is always free to customise the color based on the celebration color code.

Well, I still disagree with not including the black colour. These are my reasons:

1. We should try to be as thorough as possible to implement everything that is offically in the liturgy of the Roman Catholic Church. Black is an official liturgical colour, therefore it should be implemented.

2. If we strive for the simplicity that much, so why do we have gold colour when it is not officially (i.e. generally in the whole Church) included in the list of liturgical colours? (Yes, episcopal conferences _may_ add **more precious, sacred vestments**, incl gold and silver colours, but that is added in those dioceses _only_.)

3. I think we should add black colour and strive _less_ for the simplicity and _more_ for the liturgical accuracy. We should implement a way to use multiple colours (actually: one or two) for a particular celebration, because a celebration might have black or purple colour, and another one pink or purple colour.

4. You say that `[t]hen everyone is always free to customise the color based on the celebration color code.` But at different place, when you were talking (I think) about localisation of the liturgical colours within the object romcal outputs to its clients, you suggest to add 2 different keys (1. a constant colour name in English like `GREEN` and 2. a localised version of that colour like `zelená` in Slovak) for the same colour. Even in that case, _everyone_ could localised the colour names from English without the need of sending them the localised name. So my question is: why do you have different approach for such a quite similar thing?

**Comment by emagnier** [comment]
Because

- The Romcal API should be accurate as much as possible, without giving a subjective "array" of choices. As a developer, when building something on top of Romcal, we want romcal to provide more precise, objective and predictable information, without having to manage a choice at this level.

- Afterwards, you are entirely free to customize data provided by the Romcal API (and on the light of liturgical instructions). Returned data from Romcal isn't for end users. But as a developer working on an app, a UI or whatever on top of Romcal, you are free to customize any information (color name, hex code...), based on the color or celebration keys, to display eveything the way you want. So if you want to use black for All Soul’s, this is the perfect place to do it.

- You are right, the `Gold` color is nowhere used and could be removed.

- In your last point (4), the proposition to output a localized name isn't the same thing. The output of the localized name is just sugar in the API (and as a developer, you are free to use it or not), and it remains objective (since it’s just the localized equivalent of the color key). But indeed this is something that can be useful or not for a developer, depending of the needs, but not essential.

**Comment by tukusejssirs** [comment]
Okay, I won’t argue anymore, but I still think black colour should be included in romcal. Still, I leave a comment on the last paragraph of the previos comment.

---

> * In your last point (4), the proposition to output a localized name isn't the same thing. The output of the localized name is just sugar in the API (and as a developer, you are free to use it or not), and it remains objective (since it’s just the localized equivalent of the color key). But indeed this is something that can be useful or not for a developer, depending of the needs, but not essential.

`localized name is just sugar in the API`: How different is this _sugar_ from additional colour (incl colour array)? One could still use `colour[0]` to use the default colour _always_, other person might want to process the whole array and thus he might use `colour[0] = purple` and `colour[1] = black`.

**Comment by emagnier** [comment]
Trying to find a median approach to deal with the points I've exposed above, and to be compliant with the General instruction of the Roman Missal... This might be addressed by one of the solutions above:

1. Specify liturgical colors in an array, with the recommendation to always specify at first position the generally most used color: `colors: ['PURPLE', 'BLACK']` (this is your suggestion in the previous comment). Especially since the black color is only proposed as an alternative to the default purple color, for the Masses for the Dead.

2. Or specify another property: `alternativeColor: 'BLACK'`.

TBH I'm not very up to add another property (the 2nd point), so the first approach might be the happy medium 👍 .

As you said, this situation might be only limited to Laetare, Gaudete and the All Soul’s Day.

**Comment by tukusejssirs** [comment]
Thanks for accepting my approach! I wasn’t expecting that! :smiley:

**Comment by emagnier** [comment]
Addressed on https://github.com/romcal/romcal/pull/250.
