### ISSUE TITLE
Custom/Proper in psalter weeks

### ISSUE THREAD

**Issue by tukusejssirs** [pejulian/romcal#220]
In the Liturgy of the Hours, we use 4 weeks. On special days (e.g. on Easter Sunday), we don’t usually output the psalter week number, however, we denote that it is a custom (or Proper?) celebration outside of the usual psalter weeks.

I have no idea how to describe this properly, however, this is the practice at least in Slovakia and Hungary. You can see it [here](https://github.com/breviar-sk/Liturgia-hodin-online/blob/master/source/poznamky/2019-10-23-rimske-cislice/2019-Liturgicky-kalendarik.pdf) where is hosted the _(Small) Liturgical Calendar 2019_, where you can find the psalter week numbers at the right side of each celebration (I-IV + V; V stands for _vlastna_, i.e. literary _custom_; I think that in English the word _proper_ is used here).

**Comment by emagnier** [comment]
The psalter week cycle was already part of romcal 1.x, but was buggy.
It has been redone in the `_F-TypeScript` branch. Please have a look to https://github.com/romcal/romcal/blob/_F-TypeScript/docs/data-output.md#psalter-weeks

**Comment by tukusejssirs** [comment]
@emagnier, you still haven’t commented on the issue raised in the description of this PR.

**Comment by emagnier** [comment]
Yes I read too fast your first post. But I don't see what’s the issue.

In the liturgy of the hours, almost all weekdays (actually almost all liturgical day in general) are effectively leaning on the psalter weeks cycle. When you have a memorial, the prayers to conclude the office could be different (generally took from the missal). When you have a feast, more elements can be changed (e.g. specific hymns, some or all different psalms and canticles...).

And when you have a solemnity (or special days like in paschal triduum), generally everything is different, because this liturgical day provides its proper divine offices. This is where some book editions or document instructions could display `V` or anything else (or usually nothing). So we don't take the wrong divine office by mistake, if we forgot to check if a proper office already exists in the breviary.

Like the psalter week cycle, we have the same scenario with the Sundays and weekdays cycle. Just as the psalter week cycle is computed for a whole week, these 2 other cycles are computing for the whole liturgical year. On weekdays, we still can know in which Sunday cycle we are, even if this information isn't needed on weekdays (but there are exceptions!). Same for any weekdays not it the ordinary time, where the weekday cycle isn't needed.

If the day is a solemnity or any other special day, I think it's the responsibility to the developer using romcal (or a third-party app managing the liturgical content) to display or not – or display differently – the psalter week cycle for each day. Especially that romcal isn't computing and providing the divine offices content.

**Comment by tukusejssirs** [comment]
> Yes I read too fast your first post. But I don't see what’s the issue.

What I meant by this issue is to _add_ `proper` item into the psalter week list.

AFAIK the usual psalter weeks (1 through 4) is _not_ used for celebrations which have proper celebration texts, e.g. when the celebration is a solomnity. You can re-read the second paragraph of the issue description and see the [linked PDF](https://github.com/breviar-sk/Liturgia-hodin-online/blob/master/source/poznamky/2019-10-23-rimske-cislice/2019-Liturgicky-kalendarik.pdf) of how exactly it is used in practice.

If you don’t want to add a `proper` item to the psalter week list, we could implement a way to output if the celebration has proper texts or not.

**Comment by emagnier** [comment]
I invite you to read again my last comment, I well understood your comment :)

But as I also wrote, in the liturgy it's never all or nothing: a proper divine office is still part of another liturgical cycle. 
A memorial, a feast, and even a solemnity still lean on this week cycle, at varying degrees.
Below I took the example of the Sundays and weekday cycles, which are a similar situation. We don't remove the Sunday cycle metadata because we are in a weekday.

Yes, we generally "hide" (or replace by anything else) the week cycle when it's a solemnity, for a convenient use. But this is still important to keep this metadata, because there is always exceptions, or communities that have special needs.

romcal is a tool that provides a lot of metadata, that you are free to use or not as a developer:

> If the day is a solemnity or any other special day, I think it's the responsibility to the developer using romcal (or a third-party app managing the liturgical content) to display or not – or display differently – the psalter week cycle for each day. Especially that romcal isn't computing and providing the divine offices content.

**Comment by emagnier** [comment]
On second thought, I changed my mind and I'm open to a separated metadata, which could provide this information, for a convenient use of the breviary. It would take the weekdayCycle value by default, except if you overwrite it by the `PROPER` value, in its liturgical day definition. 
Potentially, it might also take the `PROPER` value automatically when it's a solemnity.
What do you think? We also need to give a different name for this property, different from `weekdayCycle`.

**Comment by tukusejssirs** [comment]
It’s a perfect compromise! I’ve just suggested something similar to do with the non-title titles (see #253).

> We also need to give a different name for this property

I think it should be something related to the Proper, as the texts/preface/whatever are Proper for the particular celebration, whether they are taken from the Proper or Common part of the liturgical books.

**Comment by emagnier** [comment]
Addressed on https://github.com/romcal/romcal/pull/250.
