### ISSUE TITLE
Rename the `source` key used in celebration definitions

### ISSUE THREAD

**Issue by tukusejssirs** [pejulian/romcal#247]
I would suggest to rename the `source` key used in celebration definitions to something else, as IMHO a `source` should be the source from where we got the celebration metadata (see #234).

**Comment by emagnier** [comment]
I agree, it's quite confusing.
It's actually directly related to the l10n files: it corresponds to the namespace where to find the value of a locale key.

Better tooling to manage i18n in general are still on the todo list. But in the meantime we could find a better and less confusing name.

What about `localeNamespace`? @tukusejssirs what do you think?

**Comment by tukusejssirs** [comment]
> I agree, it's quite confusing.
> It's actually directly related to the l10n files: it corresponds to the namespace where to find the value of a locale key.
>
> Better tooling to manage i18n in general are still on the todo list.

Indeed, a request for a l10n tool was one of my first issues I created on romcal (see #43). :wink: The issue description is not updated to my latest suggestions though, therefore one needs to read the whole discussion. Basically: now I suggest to use _Martyrologium Romanum_ (2004) as the base for the l10n tool data + many tables I created on [Google Sheets](https://docs.google.com/spreadsheets/d/1huvnEXr9QiCUT3-TuMIxxxG4xggMqG-Vq1E0QwVmBY8). I am in the process of proofreading the OCR’ed version, then I need to fill those tables with all the data from MR2004, finally need to search for the rest. I want to finish the proofreading by the end of August 2021 and filling the data from MR2004 to the tables by the end of 2021. Hopefully, by the end of 2022 we could have filled all the tables in Latin, English, Slovak, Czech, and with your help French. If we (I) find some contributors who would help me, we could accomplish this sooner. One thing I need to know before I start filling the tables, is how should I do this: should I fill the tables on Google Sheets or use a MongoDB database or how? I need to know this, because I wish we could create a `sanctoral` package (feel free to suggest a better name) with all these tables/data. At build time, romcal could select (somehow) just those `sanctoral` data which is required _by the builder_ (person), like only for specific calendars (e.g. only for `general`; only for French-speaking countries; only for European countries; only for a list of specific countries) or up to a calendar level (see calendar inheritence; e.g. only up to national calendars). This could make the build romcal smaller for those who require it, while I could build it with all the available `sanctoral` data (ideally, I’d like to run romcal from the repository, while to JS/TS script would not be required to run in the repo root).

Sorry for being off topic a bit. :wink:

> But in the meantime we could find a better and less confusing name.
> 
> What about `localeNamespace`? @tukusejssirs what do you think?

Well, I am not againt `localeNamespace`, but it is quite long IMHO (although we have much long key names already; and I don’t really consider this a big problem).

Is it really a _namespace_? Should we call it like that?

What about `group` or `type` (without `locale` prefix)?

**Comment by emagnier** [comment]
It's actually a namespace. Maybe we could simply call it `namespace` as you are suggesting. 👍 
I like less `group` or `type` because I still find them confusing.

---

I know that mentioning l10n/i18n tooling will be the trigger keyword 😉 
Just to answer you very quickly (we should discuss that elsewhere to not continue the off-topic here):
1. Within the romcal repo, data will always be stored in files (`.ts`, or even better in `.json` or `.yaml` files), to keep simplicity and make contribution easy. And indeed we will have to find an easy way to reduce file size for environments that require it (front-end/browser).
2. Be able to connect a database like MongoDB should be possible if we redesign the l10n management (a more modular architecture) and ease the import/export data from APIs. But this might not be the first priority.
3. If you already use Google Spreadsheet, I guess you can continue to work with it for now (don't forget to do offline backup time to time). Then data should be easy to extract from a well organized spreadsheet.
4. Last point, but the most important: a big thank you for all of this hard work you are doing! This is very valuable!

**Comment by tukusejssirs** [comment]
> It's actually a namespace. Maybe we could simply call it `namespace` as you are suggesting. 👍
> I like less `group` or `type` because I still find them confusing.

Okay, let’s name it `nanespace`. 👍

**Comment by emagnier** [comment]
Has been fixed in #282.
