### ISSUE TITLE
Add a way to compute calendar for no calendar

### ISSUE THREAD

**Issue by tukusejssirs** [pejulian/romcal#252]
I think it might be good idea to add an option to compute a calendar for no calendar (neither GRC nor any particular calendar).

This might be usefull for debugging purposes or even teaching/studying purposes.

I suggest to add `none` value to the calendar list or and empty one.

**Comment by emagnier** [comment]
This is a good idea. However we still need the context of a year to compute the liturgical calendar. Otherwise romcal will not be able to compute correctly a calendar.

Instead I propose a `raw: true` option that will output absolutely all liturgical days, even the one that are not relevant, for a specified calendar.

I've already implemented this feature on a private fork, this allow me to retrieve absolutely all possible liturgical days.

**Comment by tukusejssirs** [comment]
I agree with you that it is a better idea (from the implementation point of view at least). However, I wanted to generate a calendar with the (let’s say) basic celebrations, like Sundays, Paschal Triduum, Ascension, Corpus Christi, Assumption (and probably some others). I know that this might be a bit complicated as we as about to merge `celebrations.ts` into `general.ts`.

**Comment by emagnier** [comment]
Actually, you can already do it very easily by filtering the calendar results.

**Comment by emagnier** [comment]
This is kind of related to https://github.com/romcal/romcal/issues/262.

Note that in addition to filter JS options, you can also retrieve one `LiturgicalDay` by its key:
https://github.com/romcal/romcal#get-one-liturgical-day-getoneliturgicaldaykey-options

**Comment by tukusejssirs** [comment]
> This is kind of related to #262.

Yes, it is related, but I think that this issue (#252) is actually solved by `getAllDefinitions()`, but #262 is not, because by a calendar proper I mean of list of celebrations in a particular calendar (look at some examples [here](https://drive.google.com/drive/u/1/folders/1Dbq1l77eDgqwfSVXtfdCOyfHEoRjOeQJ)). A related issue to #262 is #234 (as noted in the issue description of #262).

**Comment by emagnier** [comment]
All `LiturgicalDay` objects have a `fromCalendar` metadata, so you can also filter on that property if you only want the `LiturgicalDay` objects that are only defined from one (or a list of) calendar(s).

**Comment by tukusejssirs** [comment]
A newbie question: how can I filter object of objects? How can (efficiently) I can create an object with all `LiturgicalDay` objects that have a particular `fromCalendar` value? As you know, `filter()` does not work on objects.

I could output the matched objects using the following code, but I don’t think it is efficient enough:

```js
for (const key of Object.keys(romcalOutput)) {
  if (romcalOutput[key].fromCalendar === 'slovakia') {
    console.log(romcalOutput[key])
  }
}
```

I could create an array (or an object) using the same code, but isn’t there a more efficient way to filter the object?

A side question: why do we now get object of objects instead of array of objects?

**Comment by emagnier** [comment]
The most efficient way to filter an object, is converting it to an array using [`Object.entries`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries), and then convert it back to an object with [`Object.fromEntries`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/fromEntries).

```js
const filteredData = Object.fromEntries(
  Object.entries(romcalOutput).filter(([key, item]) => item.fromCalendar === 'slovakia')
)

```

---

Internally these data are treated as `Record` of `key, LiturgicalDayDef` (i.e. as `Object`). Eventually you could have the need to pick only specific items, like `romcalOutput['easter_sunday']` and `romcalOutput['peter_and_paul_apostles']`, and that's by default possible. But in fact, output data type are only modified if it's worth it (because any data manipulation have impact in terms of performance and how you pick a specific item), this is why romcal do not convert data as `Array` by default.

But for your use case, if you prefer to retrieve data as an `Array` of `Object`, you can do it easily by adding `.then(Object.values)` :

```js
const arrayData = await new Romcal().getAllDefinitions().then(Object.values);
```
