### ISSUE TITLE
Using Typescript branch - how to get mass reading consistantly?

### ISSUE THREAD

**Issue by pvanthony** [pejulian/romcal#260]
Please note that this is not an issue. I am new to programming.

I would like an example code to get the mass reading for everyday. I tried doing some code and it works for some days but not for other days. For example my code does not work on 2021-01-29. It works for 2021-01-28 as an example.
I am guessing that sometimes the array has the "base" and sometimes the array does not have the "base".

Here is the link to the test code that works most of the days.
https://romcal.sound.sg/2021/daily/
Here is an example of the same code but does not work on 2021-01-29
https://romcal.sound.sg/2021/ 

After doing the npm install, using the bundle code in the dist directory.

What am I doing wrong? What should be the correct code to get the reading of the day.
Currently I am using daily[0].name or daily[0].base.name?

Is there one consistant array key that can be called?

**Comment by emagnier** [comment]
Hi @pvanthony 

Thank you for your question 👍 

Indeed it doesn't work in all cases, because you are using the `base` property to get the `name`, which is only appended on liturgical day objects that might take precedence over the "base" _weekday_. 

On the `2021-01-28`, you have the feast of _Saint Thomas Aquinas_, which is a _memorial_, taking precedence over the _weekday_. In this situation, a `base` property is added to the liturgical day object, containing the metadata of the "overwritten" liturgical day. Theses `base` metadata are added for special needs only, and may be necessary on some rules of the liturgy of the hours.

On the `2021-01-29`, you got a "default" _weekday_. This is already a "base" liturgical day, so no need to output again theses metadata in a `base` property.

---

➡️  So in your situation, I guess you should always take the name of the main object (not from the `base` object):

```js
document.getElementById("name").innerHTML = "Liturgical Reading: " + daily[0].name;
```

Or if you absolutely need the _weekday_ name of any days, you could change your code to:
```js
const name = daily[0].base ? daily[0].base.name : daily[0].name
document.getElementById("name").innerHTML = "Liturgical Reading: " + name;
```

---

I'm closing this issue, but feel free to continue the discussion if there is still anything.

**Comment by pvanthony** [comment]
Thank you very much for the code. It works great. This has helped me much. I do appreciate it very much.
Only if you have time, I need an explanation of the code.
```
const name = daily[0].base ? daily[0].base.name : daily[0].name
```
Does the above mean the following?
A constant variable called "name" equals to daily[0].base.name if daily[0].base exist. If not then "name" equals to daily[0].name.
```
if daily[0].base == True:
   const name = daily[0].base.name;
else:
   const name = daily[0].name;
```
